name = "Korg"
uuid = "acafc109-a718-429c-b0e5-afd7f8c7ae46"
authors = ["Adam Wheeler <a.wheeler@columbia.edu>"]
version = "0.23.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.8, 0.9, 0.10"
DSP = "0.7"
FastGaussQuadrature = "0.4, 0.5"
ForwardDiff = "0.10"
HDF5 = "0.15, 0.16"
Interpolations = "0.13, 0.14"
NLsolve = "4.5"
Optim = "1.7"
LineSearches = "7"
ProgressMeter = "1"
SpecialFunctions = "1.4, 2"
StaticArrays = "1"
julia = "1.7 - 1"
