name = "Korg"
uuid = "acafc109-a718-429c-b0e5-afd7f8c7ae46"
authors = ["Adam Wheeler <adamwhlr@gmail.com>", "Matthew Abruzzo <matthewabruzzo@gmail.com>"]
version = "0.46.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
CSV = "0.8, 0.9, 0.10"
Compat = "4.10 - 4"
DSP = "0.7, 0.8"
DataFrames = "1.7.0"
DiffResults = "1"
FastGaussQuadrature = "0.4, 0.5, 1"
ForwardDiff = "1.0"
HDF5 = "0.15, 0.16, 0.17"
Interpolations = "0.16"
LazyArtifacts = "1"
LineSearches = "7"
LinearAlgebra = "1.7 - 1"
NLsolve = "4.5"
Optim = "1.7"
Pkg = "1"
ProgressMeter = "1"
SparseArrays = "1.7 - 1"
SpecialFunctions = "1.4, 2"
StaticArrays = "1"
Statistics = "1"
TableOperations = "1.2.0"
Trapz = "2"
julia = "1.7 - 1"
